name: flowation-mock

services:
  mock-postgres:
    image: postgres:16
    container_name: mock-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: ecom_password
    ports:
      - "5433:5432"
    volumes:
      - mock_postgres_data:/var/lib/postgresql/data
      - ./mock-ecommerce/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom_user -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-api:
    build: ./mock-ecommerce
    container_name: mock-api
    environment:
      DB_HOST: mock-postgres
      DB_PORT: 5432
      DB_USER: ecom_user
      DB_PASSWORD: ecom_password
      DB_NAME: ecommerce
    ports:
      - "8081:8081"
    depends_on:
      mock-postgres:
        condition: service_healthy

volumes:
  mock_postgres_data:
