spring:
  application:
    name: flowation-api-modulith
  datasource:
    url: jdbc:postgresql://localhost:4321/flowation-db
    username: fw_user
    password: fw_password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  threads:
    virtual:
      enabled: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: FlowationScheduler
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: false
          threadPool:
            threadCount: 5

server:
  port: 2121

flowation:
  execution:
    max-nesting-depth: 10

logging:
  level:
    root: WARN
    kg.ademity.flowation_api_modulith: INFO
